fix the heightmap proxy caster guy
Outer-Wilds-New-Horizons/new-horizons pull request #1002
Opened 2024-12-20 05:03 UTC by TerrificTrifid

changelog can say
- Fixed the proxy shadow caster on heightmaps, so they cast shadows onto other bodies better

2024-12-20 05:05 UTC, JohnCorby approved these changes

2025-01-06 01:21 UTC, xen-42 requested changes

2025-01-06 01:21 UTC, xen-42 commented on NewHorizons/External/Modules/AsteroidBeltModule.cs
> +        [Range(0f, double.MaxValue)]
its a float not a double

2025-01-06 01:21 UTC, xen-42 commented on NewHorizons/Builder/Body/HeightMapBuilder.cs
> +
Add a comment here saying that we only do the group stuff if LOD is on bc the only times LOD is off is for title screen and proxies

2025-01-06 01:21 UTC, xen-42 commented on NewHorizons/Builder/Body/AsteroidBeltBuilder.cs
> +                if (belt.assetBundle != null || belt.path != null)
since these are strings should probably do string.IsNullOrEmpty

2025-01-06 01:21 UTC, xen-42 commented on NewHorizons/External/Modules/AsteroidBeltModule.cs
> +        /// Should they be randomly oriented, or all pointing towards the center.
Since this only affects details not procgen we should say that

2025-01-06 03:11 UTC, xen-42 approved these changes

2025-01-06 04:18 UTC, merged