1.6.0
Outer-Wilds-New-Horizons/new-horizons pull request #337
Opened 2022-09-01 00:58 UTC by xen-42

2022-09-04 03:15 UTC, MegaPiggy approved these changes

2022-09-10 19:14 UTC, MegaPiggy requested changes
😠

2022-09-12 17:01 UTC, xen-42 commented
@MegaPiggy what does that mean

2022-09-16 04:00 UTC, JohnCorby approved these changes

2022-09-16 04:06 UTC, merged