Disable starlights when out of range
Outer-Wilds-New-Horizons/new-horizons pull request #345
Opened 2022-09-03 00:17 UTC by TerrificTrifid

Fixes transparent stuff

2022-09-03 00:18 UTC, TerrificTrifid commented
- [ ] Fix NRE when sun is destroyed

2022-09-04 03:14 UTC, MegaPiggy approved these changes

2022-09-15 04:15 UTC, merged

2022-09-15 04:19 UTC, xen-42 requested changes

2022-09-15 04:19 UTC, xen-42 commented on NewHorizons/Components/SizeControllers/StarEvolutionController.cs
> +            StarLightController.RemoveStarLight(gameObject.FindChild("SunLight").GetAddComponent<Light>());
Don't use GetAddComponent, just use GetComponent

2022-09-15 04:19 UTC, xen-42 commented on NewHorizons/Components/StarLightController.cs
>                  if (PlayerState.InMapView())
Since you brought the origin part out of this for loop, bring this if statement with it

2022-09-15 04:19 UTC, xen-42 commented on NewHorizons/Components/StarLightController.cs
> +            foreach (var light in _lights)
This feels inefficient, we already loop through all stars now we're essentially looping through them all again to check their lights too. But I guess some stars don't have StarControllers so it isn't a 1:1 thing anyway.

2022-09-15 04:19 UTC, xen-42 commented on NewHorizons/Components/StarLightController.cs
> +                return;
Instead of returning here just just put what comes next inside an `else`, makes it clearer