Fog Ramp Path
Outer-Wilds-New-Horizons/new-horizons pull request #569
Opened 2023-04-04 07:17 UTC by JohnCorby

## Major features
-

## Minor features
-
 add support for custom fogColorRampTexture

## Improvements
-

## Bug fixes
-

2023-04-21 04:47 UTC, JohnCorby commented
classic tested this and it "didnt work" but i put that in quotes because i dont trust classic

2023-07-01 23:47 UTC, JohnCorby commented
closing for now. classic appears to not need this feature, nor does anyone else

2023-07-18 06:03 UTC, xen-42 commented
I say let's just merge it

2023-07-18 06:03 UTC, xen-42 approved these changes

2023-07-18 06:04 UTC, xen-42 requested changes

2023-07-18 06:04 UTC, xen-42 commented on NewHorizons/Builder/Atmosphere/FogBuilder.cs
>              var colorRampTexture = atmo.fogTint == null ? _ramp : ImageUtilities.TintImage(_ramp, atmo.fogTint.ToColor());
Wait yeah don't tint just do an if else

2023-07-19 04:10 UTC, xen-42 approved these changes

2023-07-19 04:10 UTC, merged