Shuttle
Outer-Wilds-New-Horizons/new-horizons pull request #667
Opened 2023-07-22 15:42 UTC by xen-42

## Major features
- Implement Nomai shuttles and gravity cannons

2023-07-22 17:49 UTC, xen-42 commented
Similar to the ship log API changes we should make a way of loading Nomai text from an XElement object instead of requiring a file path, then we can use that to make the gravity cannon computer text. It's a single line so we should just take in a string instead of loading an entire xml. We would also have the option of dynamically creating the line if it isn't supplied by just using the name of the planet the shuttle is on.

2023-08-05 04:06 UTC, MegaPiggy approved these changes

2023-08-05 04:17 UTC, merged

2023-08-05 04:34 UTC, JohnCorby requested changes

2023-08-05 04:34 UTC, JohnCorby commented on NewHorizons/Builder/Props/DetailBuilder.cs
> +            if (component is Sector s && existingSectors.Contains(s.GetParentSector()))
should there be a ! here?

2023-08-05 04:34 UTC, JohnCorby commented on NewHorizons/Builder/Props/DetailBuilder.cs
> +                var existingSectors = new HashSet<Sector>(prop.GetComponentsInChildren<Sector>());
should this include inactive sectors?