Allow adding an xml to an existing dialogue that had a null asset
Outer-Wilds-New-Horizons/new-horizons pull request #868
Opened 2024-05-31 10:09 UTC by MegaPiggy

## Bug fixes

- If `pathToExistingDialogue` points to a dialogue object that has a null asset, it will now set its asset to yours instead of erroring.
- We now search in the body for `pathToExistingDialogue`. You no longer have to put the root object at the beginning of the path.

2024-06-01 23:48 UTC, JohnCorby requested changes
im almost certain its not possible to have a dialogue tree with no asset, because it would NRE in LoadXml
maybe ur thinking of chert???

also no longer requiring root in `pathToExistingDialogue` is a breaking change, no?

2024-06-01 23:53 UTC, MegaPiggy commented
This is pretty much for unity assets so that you can set your xml with nh

2024-06-01 23:55 UTC, MegaPiggy commented
> also no longer requiring root in pathToExistingDialogue is a breaking change, no?

It isn't because it still does the old way. I noticed a ton of mods don't do root, which meant it just searched for the name of the last object in the path instead.

2024-06-04 02:59 UTC, xen-42 approved these changes
lgtm

2024-06-04 03:01 UTC, xen-42 commented
Using SearchUtilities instead of searching the children like every other config thing ever was a total oversight. Unless there is actually a mod that relies on it doing that (and is editing dialogue on one planet from a config for another for some reason) then we should just remove that part outright

2024-06-04 03:50 UTC, xen-42 commented
Once this PR is merged in Reactive Hearthians we can just remove the SearchUtility part at all because that should not work and it would set a bad and confusing precedent to even allow it to work. <https://github.com/omega-fallon/ReactiveHearthians/pull/2>

2024-06-04 03:55 UTC, JohnCorby approved these changes

2024-06-04 09:13 UTC, merged